# -*- coding: utf-8 -*-
# Copyright (C) 2025 CEA - All Rights Reserved
# 
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syscalls.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esyscalls.proto\"g\n\x07Syscall\x12\x12\n\nsyscall_id\x18\x01 \x01(\r\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x0c\n\x04ppid\x18\x03 \x01(\r\x12\x14\n\x0cprocess_name\x18\x04 \x01(\t\x12\x17\n\x0ftimestamp_enter\x18\x05 \x01(\x04\"&\n\x08Syscalls\x12\x1a\n\x08syscalls\x18\x01 \x03(\x0b\x32\x08.Syscallb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'syscalls_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYSCALL._serialized_start=18
  _SYSCALL._serialized_end=121
  _SYSCALLS._serialized_start=123
  _SYSCALLS._serialized_end=161
# @@protoc_insertion_point(module_scope)
